version: '3.8'

volumes:
  detective_announcer_bot_database_volume:

services:

  detective_announcer_bot_backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: python main.py
    env_file: .env
    volumes:
      - .:/app
    restart: unless-stopped
